### ISSUE TITLE
Testing 0 sided dataframes

### ISSUE THREAD

**Issue by honno** [honno/dataframe-interchange-tests#7]
Do we generate examples that
1. have no columns
2. have no rows

For both instances I need to learn/clarify if the instance is:
* supported by the spec
* going to be ever used practically (i.e. if not, may not be worth if the suite finds inconsequential bugs like https://github.com/vaexio/vaex/issues/2094 over and over again, even if Hypothesis will find other failing examples)

It could be the case they're supported, but we can fairly assume some methods won't work and thus skip generating the respective instance for any related tests.

**Comment by rgommers** [comment]
Yes, I think they are relevant and it'd be nice if behavior was consistent.

**Comment by honno** [comment]
So the solution I've come up with is to test 0-sided dfs separately

https://github.com/honno/dataframe-interchange-tests/blob/056846dac79c3722fc7082b5eaff255c1764a5cb/tests/test_dataframe_object.py#L12-L30

whilst skipping their generation for all the other tests, as otherwise it gets pretty noisy.
